from  ubuntu:18.04

RUN apt-get update

RUN apt-get install wget -y

RUN apt-get install -y docker.io

WORKDIR /home

RUN mkdir agent

COPY ./ ./agent

RUN mkdir golang

WORKDIR /home/golang

RUN wget https://studygolang.com/dl/golang/go1.12.4.linux-amd64.tar.gz

RUN tar -zxf go1.12.4.linux-amd64.tar.gz

WORKDIR /home/agent

RUN /home/golang/go/bin/go build

CMD ./agent
