#!/bin/bash

# Copyright (c) Microsoft Corporation
# All rights reserved.
#
# MIT License
#
# Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated
# documentation files (the "Software"), to deal in the Software without restriction, including without limitation
# the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and
# to permit persons to whom the Software is furnished to do so, subject to the following conditions:
# The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED *AS IS*, WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING
# BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
# NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM,
# DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
#
#
# Copyright (c) Peking University 2018
#
# The software is released under the Open-Intelligence Open Source License V1.0.
# The copyright owner promises to follow "Open-Intelligence Open Source Platform
# Management Regulation V1.0", which is provided by The New Generation of 
# Artificial Intelligence Technology Innovation Strategic Alliance (the AITISA).

function install_dgx2_driver() {
    DGX2_DRIVER=410.79
    DRIVER_PATH=/var/drivers/nvidia/${DGX2_DRIVER}
    CURRENT_DRIVER=/var/drivers/nvidia/current
    [[ -e ${CURRENT_DRIVER} ]] && return 0

    mkdir -p ${DRIVER_PATH}
    ln -s ${DRIVER_PATH} ${CURRENT_DRIVER}
    mkdir ${DRIVER_PATH}/bin ${DRIVER_PATH}/lib ${DRIVER_PATH}/lib64 ${DRIVER_PATH}/share
    cp /mnt/usr/bin/nvidia-* ${DRIVER_PATH}/bin/ || return 1
    find /mnt/usr/lib/x86_64-linux-gnu -regextype "posix-egrep" -regex ".*libcuda.*|.*libEGL.*|.*libGL.*|.*libnv.*|.*libOpen.*|.*nvidia.*" -exec cp {} ${DRIVER_PATH}/lib \;
    find /mnt/usr/lib/x86_64-linux-gnu -regextype "posix-egrep" -regex ".*libcuda.*|.*libEGL.*|.*libGL.*|.*libnv.*|.*libOpen.*|.*nvidia.*" -exec cp {} ${DRIVER_PATH}/lib64 \;
    return 0
}

if lspci | grep -qE "[0-9a-fA-F][0-9a-fA-F]:[0-9a-fA-F][0-9a-fA-F].[0-9] (3D|VGA compatible) controller: NVIDIA Corporation.*"; then
    if [[ $HOSTNAME == DGX* ]] ; then
        echo processing DGX2 NVIDIA driver ...
        install_dgx2_driver || exit $?
        echo NVIDIA gpu detected, drivers installed
    else
        ./install-nvidia-drivers || exit $?
        echo NVIDIA gpu detected, drivers installed
        ./enable-nvidia-persistenced-mode.sh || exit $?
    fi
else
    echo NVIDIA gpu not detected, skipping driver installation
fi

mkdir -p /jobstatus
touch /jobstatus/jobok

while true; do sleep 1000; done
