// +build !ignore_autogenerated

/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by deepcopy-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
	types "k8s.io/apimachinery/pkg/types"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CompletionPolicy) DeepCopyInto(out *CompletionPolicy) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CompletionPolicy.
func (in *CompletionPolicy) DeepCopy() *CompletionPolicy {
	if in == nil {
		return nil
	}
	out := new(CompletionPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ContainerTerminatedInfo) DeepCopyInto(out *ContainerTerminatedInfo) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ContainerTerminatedInfo.
func (in *ContainerTerminatedInfo) DeepCopy() *ContainerTerminatedInfo {
	if in == nil {
		return nil
	}
	out := new(ContainerTerminatedInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EventPolicy) DeepCopyInto(out *EventPolicy) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EventPolicy.
func (in *EventPolicy) DeepCopy() *EventPolicy {
	if in == nil {
		return nil
	}
	out := new(EventPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReplicaStatus) DeepCopyInto(out *ReplicaStatus) {
	*out = *in
	in.TransitionTime.DeepCopyInto(&out.TransitionTime)
	if in.StartAt != nil {
		in, out := &in.StartAt, &out.StartAt
		*out = (*in).DeepCopy()
	}
	if in.FinishAt != nil {
		in, out := &in.FinishAt, &out.FinishAt
		*out = (*in).DeepCopy()
	}
	if in.PodUID != nil {
		in, out := &in.PodUID, &out.PodUID
		*out = new(types.UID)
		**out = **in
	}
	if in.TerminatedInfo != nil {
		in, out := &in.TerminatedInfo, &out.TerminatedInfo
		*out = new(ContainerTerminatedInfo)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReplicaStatus.
func (in *ReplicaStatus) DeepCopy() *ReplicaStatus {
	if in == nil {
		return nil
	}
	out := new(ReplicaStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RetryPolicy) DeepCopyInto(out *RetryPolicy) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RetryPolicy.
func (in *RetryPolicy) DeepCopy() *RetryPolicy {
	if in == nil {
		return nil
	}
	out := new(RetryPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TaskRole) DeepCopyInto(out *TaskRole) {
	*out = *in
	out.CompletionPolicy = in.CompletionPolicy
	out.RetryPolicy = in.RetryPolicy
	if in.EventPolicies != nil {
		in, out := &in.EventPolicies, &out.EventPolicies
		*out = make([]EventPolicy, len(*in))
		copy(*out, *in)
	}
	in.Pod.DeepCopyInto(&out.Pod)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TaskRole.
func (in *TaskRole) DeepCopy() *TaskRole {
	if in == nil {
		return nil
	}
	out := new(TaskRole)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TaskRoleStatus) DeepCopyInto(out *TaskRoleStatus) {
	*out = *in
	in.TransitionTime.DeepCopyInto(&out.TransitionTime)
	if in.ReplicaStatuses != nil {
		in, out := &in.ReplicaStatuses, &out.ReplicaStatuses
		*out = make([]ReplicaStatus, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TaskRoleStatus.
func (in *TaskRoleStatus) DeepCopy() *TaskRoleStatus {
	if in == nil {
		return nil
	}
	out := new(TaskRoleStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TaskSet) DeepCopyInto(out *TaskSet) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	if in.Status != nil {
		in, out := &in.Status, &out.Status
		*out = new(TaskSetStatus)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TaskSet.
func (in *TaskSet) DeepCopy() *TaskSet {
	if in == nil {
		return nil
	}
	out := new(TaskSet)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TaskSet) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TaskSetList) DeepCopyInto(out *TaskSetList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]TaskSet, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TaskSetList.
func (in *TaskSetList) DeepCopy() *TaskSetList {
	if in == nil {
		return nil
	}
	out := new(TaskSetList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TaskSetList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TaskSetSpec) DeepCopyInto(out *TaskSetSpec) {
	*out = *in
	out.RetryPolicy = in.RetryPolicy
	if in.Roles != nil {
		in, out := &in.Roles, &out.Roles
		*out = make([]TaskRole, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TaskSetSpec.
func (in *TaskSetSpec) DeepCopy() *TaskSetSpec {
	if in == nil {
		return nil
	}
	out := new(TaskSetSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TaskSetStatus) DeepCopyInto(out *TaskSetStatus) {
	*out = *in
	in.TransitionTime.DeepCopyInto(&out.TransitionTime)
	if in.ControlUnitUID != nil {
		in, out := &in.ControlUnitUID, &out.ControlUnitUID
		*out = new(types.UID)
		**out = **in
	}
	in.CreatedAt.DeepCopyInto(&out.CreatedAt)
	if in.StartAt != nil {
		in, out := &in.StartAt, &out.StartAt
		*out = (*in).DeepCopy()
	}
	if in.FinishAt != nil {
		in, out := &in.FinishAt, &out.FinishAt
		*out = (*in).DeepCopy()
	}
	if in.TaskRoleStatus != nil {
		in, out := &in.TaskRoleStatus, &out.TaskRoleStatus
		*out = make([]TaskRoleStatus, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TaskSetStatus.
func (in *TaskSetStatus) DeepCopy() *TaskSetStatus {
	if in == nil {
		return nil
	}
	out := new(TaskSetStatus)
	in.DeepCopyInto(out)
	return out
}
