{
 "title": "TaskMetrics",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "pod", "query": "label_values(pod)" },
   { "name": "pod_name", "query": "label_values(pod_name)" }
  ]
 },
 "panels": [
  { "title": "$pod", "type": "text", "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU usage rate (1m avg)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "percentunit", "label": "cores" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{pod_name=\"$pod_name\"}[1m]) or rate (container_cpu_usage_seconds_total{pod=\"$pod\"}[1m]))",
     "legendFormat": "CPU usage rate (1m avg)"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 3 },
   "yaxes": [
    { "format": "decbits" }
   ],
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{pod_name=\"$pod_name\"} or container_memory_working_set_bytes{pod=\"$pod\"})",
     "legendFormat": "Memory usage"
    }
   ]
  },
  {
   "title": "GPU utilization",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "dcgm_gpu_utilization{pod_name=\"$pod_name\"} or dcgm_gpu_utilization{pod=\"$pod\"}",
     "legendFormat": "GPU utilization"
    }
   ]
  },
  {
   "title": "GPU memory utilization",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "dcgm_mem_copy_utilization{pod_name=\"$pod_name\"} or dcgm_mem_copy_utilization{pod=\"$pod\"}",
     "legendFormat": "GPU memory utilization"
    }
   ]
  },
  {
   "title": "Filesystem usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "decbits" }
   ],
   "targets": [
    {
     "expr": "sum (container_fs_usage_bytes{device=~\"^/dev/.*$\",pod_name=\"$pod_name\"} or container_fs_usage_bytes{device=~\"^/dev/.*$\",pod=\"$pod\"})",
     "legendFormat": "filesystem usage"
    }
   ]
  },
  {
   "title": "Network I/O (1m avg)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{pod_name=\"$pod_name\"}[1m]) or rate(container_network_receive_bytes_total{pod=\"$pod\"}[1m]))",
     "legendFormat": "Received"
    },
    {
     "expr": "sum (rate (container_network_transmit_bytes_total{pod_name=\"$pod_name\"}[1m]) or rate(container_network_receive_bytes_total{pod=\"$pod\"}[1m]))",
     "legendFormat": "Sent"
    }
   ]
  }
 ]
}
{
 "title": "ClusterMetrics",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "Node",
    "query": "label_values(kubernetes_io_hostname)"
   }
  ]
 },
 "panels": [
  {
   "title": "Node Number",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(kubelet_node_config_error{instance=~\".+\"})"
    }
   ]
  },
  {
   "title": "Cluster GPU usage",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 12, "x": 6, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": " sum((count(dcgm_gpu_utilization{container_name=~\".+\"} or vector(0))-1) / count(dcgm_gpu_temp{uuid=~\".+\"}) or vector(0))*100"
    }
   ]
  },
  {
   "title": "Used GPUs",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(dcgm_gpu_utilization{container_name=~\".+\"} or vector(0))-1"
    }
   ]
  },
  {
   "title": "Total GPUs",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(dcgm_gpu_temp{uuid=~\".+\"} or vector(0)) - 1"
    }
   ]
  },
  {
   "title": "Cluster Network I/O pressure",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_network_receive_bytes_total{kubernetes_io_hostname=~\"^$Node$\"}[1m]))",
     "legendFormat": "Received"
    },
    {
     "expr": "- sum (rate (container_network_transmit_bytes_total{kubernetes_io_hostname=~\"^$Node$\"}[1m]))",
     "legendFormat": "Sent"
    }
   ]
  },
  {
   "title": "Cluster GPU utilization (avg)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 8 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum((sum(dcgm_gpu_utilization{pod_name=~\".*\"}) / count(dcgm_gpu_utilization{pod_name=~\".*\"}) ) or vector(0))",
     "legendFormat": "Cluster GPU utilization(avg)"
    }
   ]
  },
  {
   "title": "Cluster GPU memory utilization(avg)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 8 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum((sum(dcgm_mem_copy_utilization{pod_name=~\".+\"}) / count(dcgm_gpu_utilization{pod_name=~\".+\"})) or vector(0))",
     "legendFormat": "Cluster GPU memory utilization(avg)"
    }
   ]
  },
  {
   "title": "Cluster CPU usage (1m avg)",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 15 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{id=\"/\",kubernetes_io_hostname=~\"^$Node$\"}[1m])) / sum (machine_cpu_cores{kubernetes_io_hostname=~\"^$Node$\"}) * 100"
    }
   ]
  },
  {
   "title": "Cluster memory usage",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 15 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{id=\"/\",kubernetes_io_hostname=~\"^$Node$\"}) / sum (machine_memory_bytes{kubernetes_io_hostname=~\"^$Node$\"}) * 100"
    }
   ]
  },
  {
   "title": "Cluster filesystem usage",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 15 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (container_fs_usage_bytes{device=~\"^/dev/.*$\",id=\"/\",kubernetes_io_hostname=~\"^$Node$\"}) / sum (container_fs_limit_bytes{device=~\"^/dev/.*$\",id=\"/\",kubernetes_io_hostname=~\"^$Node$\"}) * 100"
    }
   ]
  },
  {
   "title": "Used",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 20 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{id=\"/\",kubernetes_io_hostname=~\"^$Node$\"}[1m]))"
    }
   ]
  },
  {
   "title": "Total",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 20 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (machine_cpu_cores{kubernetes_io_hostname=~\"^$Node$\"})"
    }
   ]
  },
  {
   "title": "Used",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 20 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{id=\"/\",kubernetes_io_hostname=~\"^$Node$\"})"
    }
   ]
  },
  {
   "title": "Total",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 20 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (machine_memory_bytes{kubernetes_io_hostname=~\"^$Node$\"})"
    }
   ]
  },
  {
   "title": "Used",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 20 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (container_fs_usage_bytes{id=\"/\",kubernetes_io_hostname=~\"^$Node$\"})"
    }
   ]
  },
  {
   "title": "Total",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 20 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (container_fs_limit_bytes{device=~\"^/dev/.*$\",id=\"/\",kubernetes_io_hostname=~\"^$Node$\"})"
    }
   ]
  }
 ]
}